export const CONFIG_OPTIONS = 'CONFIG_OPTIONS'

export const DECOR_KEY_ROLES = 'ROLES'

export const INJECT_KEY_PUB_SUB = 'PUB_SUB'

export const SUB_TRIGGER_NEW_PENDING_ORDER =
  'NEW_PENDING_ORDER'

export const SUB_TRIGGER_NEW_COOKED_ORDER =
  'NEW_COOKED_ORDER'

export const SUB_TRIGGER_NEW_ORDER_UPDATE = `NEW_ORDER_UPDATE`
